[package]
name = "zed_cairo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zed_extension_api = "0.4.0"


[lib]
path = "src/cairo.rs"
crate-type = ["cdylib"]
